spring.application.name=gateway

server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.root=INFO
logging.file.name=logs/gateway.log
logging.file.path=logs

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=mailapp_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://mailapp
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test

spring.cloud.gateway.server.webflux.routes[1].id=users_route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://usersapi
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=gateway API
springdoc.swagger-ui.urls[1].url=/usersapi/v3/api-docs
springdoc.swagger-ui.urls[1].name=users service API

spring.cloud.gateway.server.webflux.routes[2].id=backend-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://mailapp
spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=backendService
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path

spring.cloud.gateway.server.webflux.routes[3].id=backend-service2
spring.cloud.gateway.server.webflux.routes[3].uri=lb://usersapi
spring.cloud.gateway.server.webflux.routes[3].filters[0]=CircuitBreaker=backendService
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path

resilience4j.circuitbreaker.instances.backendService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.backendService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.backendService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.backendService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.backendService.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.backendService.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.backendService2.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendService2.slidingWindowSize=10
resilience4j.circuitbreaker.instances.backendService2.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.backendService2.failureRateThreshold=50
resilience4j.circuitbreaker.instances.backendService2.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.backendService2.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.backendService2.automaticTransitionFromOpenToHalfOpenEnabled=true
