spring.application.name=gateway

server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.root=INFO
logging.file.name=logs/gateway.log
logging.file.path=logs

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=mailapp_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://mailapp
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=mailappCircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback

spring.cloud.gateway.server.webflux.routes[1].id=users_route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://usersapi
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=usersapiCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback

resilience4j.circuitbreaker.instances.mailappCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mailappCircuitBreaker.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.mailappCircuitBreaker.minimumNumberOfCalls=10

resilience4j.circuitbreaker.instances.usersapiCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.usersapiCircuitBreaker.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.usersapiCircuitBreaker.minimumNumberOfCalls=10

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=gateway API
springdoc.swagger-ui.urls[1].url=/usersapi/v3/api-docs
springdoc.swagger-ui.urls[1].name=users service API
