server.port=0

spring.application.name=mailapp

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username={cipher}8e817588221171821d3d42b0193b81245bded15e66d00e33b5c1809aacf67c76e7f546f6aba3ea5240bd9ccde9b16e84
spring.mail.password={cipher}46d76482c82cdd3ff633d58945579715f6da7eb0b20f12c0bbc44f927c6b319c1fdcf299d77db6b3465d37b1f2e2040b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=messaging
spring.kafka.consumer.auto-offset-reset=earliest
app.topic-name=test-topic
app.mailer.subject ="Test-service information"

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}

logging.level.root=INFO
logging.file.name=logs/mailapp.log
logging.file.path=logs

